name: Close stale issues

on:
  schedule:
    # 每天晚上12点运行
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v5
        with:
          days-before-stale: 30
          days-before-close: 14
          stale-issue-message: 'This issue has been marked as stale because it has not had recent activity. If you have any updates or think this should remain open, please comment below.'
          close-issue-message: 'Closing this issue due to inactivity after 30 days. Please feel free to reopen if you need more discussion.'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
